// import {
//   HintProfileFormat,
//   LetterPanelLocations,
//   PanelInitialDisplayOptions,
//   PanelTypes,
//   ProfileDisplayDefaults,
//   SearchPanelLocations,
//   StringHintDisplayOptions,
//   TrackingOptions,
// } from './hintProfilesSlice';

// export const defaultProfiles: HintProfileFormat[] = [
//   {
//     name: "Super Spelling Bee",
//     isUserCreated: false,
//     displayDefault: ProfileDisplayDefaults.Expanded,
//     trackingDefault: TrackingOptions.Both,
//     panels: [
//       {
//         name: "Basic Info",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Basic,
//         typeOptions: {
//           showWordCount: true,
//           showTotalPoints: true,
//           showPangramCount: true,
//           showPerfectPangramCount: true,
//         },
//       },
//       {
//         name: "Remaining Words",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Letter,
//         typeOptions: {
//           numberOfLetters: 1,
//           locationInWord: LetterPanelLocations.Beginning,
//           offset: 0,
//           display: StringHintDisplayOptions.WordLengthGrid,
//         },
//       },
//       {
//         name: "Starting Letters x Word Lengths",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Letter,
//         typeOptions: {
//           numberOfLetters: 2,
//           locationInWord: LetterPanelLocations.Beginning,
//           offset: 0,
//           display: StringHintDisplayOptions.WordLengthGrid,
//         },
//       },
//       {
//         name: "Word Obscurity Ranking",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.WordObscurity,
//         typeOptions: {},
//       },
//       {
//         name: "String Search",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Search,
//         typeOptions: {
//           searchLocation: SearchPanelLocations.Anywhere,
//           offset: 0,
//           display: StringHintDisplayOptions.LettersOnly,
//         },
//       },
//       {
//         name: "Definitions",
//         isCollapsed: true,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Collapsed,
//         type: PanelTypes.Definitions,
//         typeOptions: {},
//       },
//       {
//         name: "Excluded Words",
//         isCollapsed: true,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Collapsed,
//         type: PanelTypes.ExcludedWords,
//         typeOptions: {},
//       },
//     ],
//   },
//   {
//     name: "NYT Spelling Bee Buddy",
//     isUserCreated: false,
//     displayDefault: ProfileDisplayDefaults.Blurred,
//     trackingDefault: TrackingOptions.Remaining,
//     panels: [
//       {
//         name: "Basic info",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Basic,
//         typeOptions: {
//           showWordCount: true,
//           showTotalPoints: true,
//           showPangramCount: true,
//           showPerfectPangramCount: false,
//         },
//       },
//       {
//         name: "Your Grid of Remaining Words",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Remaining,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Letter,
//         typeOptions: {
//           numberOfLetters: 1,
//           locationInWord: LetterPanelLocations.Beginning,
//           offset: 0,
//           display: StringHintDisplayOptions.WordLengthGrid,
//         },
//       },
//       {
//         name: "Your Two-Letter List",
//         isCollapsed: false,
//         isBlurred: false,
//         tracking: TrackingOptions.Remaining,
//         initialDisplay: PanelInitialDisplayOptions.Expanded,
//         type: PanelTypes.Letter,
//         typeOptions: {
//           numberOfLetters: 2,
//           locationInWord: LetterPanelLocations.Beginning,
//           offset: 0,
//           display: StringHintDisplayOptions.WordCountList,
//         },
//       },
//       {
//         name: "Word Obscurity Ranking",
//         isCollapsed: false,
//         isBlurred: true,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Blurred,
//         type: PanelTypes.WordObscurity,
//         typeOptions: {},
//       },
//       {
//         name: "Definitions",
//         isCollapsed: false,
//         isBlurred: true,
//         tracking: TrackingOptions.Both,
//         initialDisplay: PanelInitialDisplayOptions.Blurred,
//         type: PanelTypes.Definitions,
//         typeOptions: {},
//       },
//     ],
//   },
// ]
